In [1]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split

#load Dataset
PATH = "/home/dtd/Documents/interpretable_machine_learning/Source Code/data/pima-indians-diabetes-database"
data = pd.read_csv(PATH + '/diabetes.csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
model = pickle.load(open(PATH + "/pima.pickle.dat", 'rb'))

In [3]:
data_full = data.copy()
X_data = data_full.drop('Outcome', axis=1)
y = data_full.Outcome

seed = 7
test_size = 0.3
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=test_size, random_state=seed)

In [4]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
590,11,111,84,40,0,46.8,0.925,45
692,2,121,70,32,95,39.1,0.886,23
492,4,99,68,38,0,32.8,0.145,33
205,5,111,72,28,0,23.9,0.407,27
709,2,93,64,32,160,38.0,0.674,23
...,...,...,...,...,...,...,...,...
579,2,197,70,99,0,34.7,0.575,62
502,6,0,68,41,0,39.0,0.727,41
537,0,57,60,0,0,21.7,0.735,67
196,1,105,58,0,0,24.3,0.187,21
175,8,179,72,42,130,32.7,0.719,36

In [5]:
data['predicted_class'] = model.predict(X_data)

In [6]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,predicted_class
0,6,148,72,35,0,33.6,0.627,50,1,1
1,1,85,66,29,0,26.6,0.351,31,0,0
2,8,183,64,0,0,23.3,0.672,32,1,0
3,1,89,66,23,94,28.1,0.167,21,0,0
4,0,137,40,35,168,43.1,2.288,33,1,1
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0
764,2,122,70,27,0,36.8,0.340,27,0,0
765,5,121,72,23,112,26.2,0.245,30,0,0
766,1,126,60,0,0,30.1,0.349,47,1,1
767,1,93,70,31,0,30.4,0.315,23,0,0

In [21]:
X_data.values

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [12]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

In [22]:
a = np.random.rand(10,1)
import time 
time1 = time.time()
dist = euclidean_distances(X_data.values, X_data.values)
time2 = time.time()
time2-time1  #0.08735871315002441

0.013365507125854492

In [23]:
dist

array([[  0.        ,  66.90348403,  54.29633528, ..., 117.7833007 ,
         43.58127217,  61.71982942],
       [ 66.90348403,   0.        , 102.51825711, ..., 118.02190998,
         53.16248681,  12.74524602],
       [ 54.29633528, 102.51825711,   0.        , ..., 130.39398885,
         59.87774486,  96.3199743 ],
       ...,
       [117.7833007 , 118.02190998, 130.39398885, ...,   0.        ,
        116.45694834, 116.0975663 ],
       [ 43.58127217,  53.16248681,  59.87774486, ..., 116.45694834,
          0.        ,  52.21198288],
       [ 61.71982942,  12.74524602,  96.3199743 , ..., 116.0975663 ,
         52.21198288,   0.        ]])